sudo: required

services:
  - docker

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pylint model/ test/ app.py
  - pytest

after_success:
  - sh .travis/deploy_dockerhub.sh
